### ISSUE TITLE
Does not work on Ruby 2.0 on Windows due to old dependency version for http_parser.rb

### ISSUE THREAD

**Issue by jarmo** [igrigorik/em-websocket#102]
Problem is that `em-websocket` has `http_parser.rb` set as its dependency with version constraint `~> 0.5.3`. That version of `http_parser.rb` does not work with Ruby 2.0 on Windows. There is however a pre-release version of `http_parser.rb` with version of `0.6.0.beta.2` which does seem to work.

Is it possible to release a new version of `em-websocket` with a different dependency version for `http_parser.rb`?

**Comment by stephan-nordnes-eriksen** [comment]
This appears to have been removed in a later PR. Why? Em-websocket does not work on windows ruby 2.0+ anymore.

**Comment by mloughran** [comment]
Not removed, updated to the released version of the gem.
