### ISSUE TITLE
http_parser.rb ~> 0.6.0 ?

### ISSUE THREAD

**Issue by kekoziar** [igrigorik/em-websocket#157]
Does this still use a runtime dependency of `http_parser.rb ~> 0.6.0` ?  It's been updated to [version 0.7.0](https://rubygems.org/gems/http_parser.rb). I'm trying to track down where in the `bundle update` path for `github-pages` it's still referring to 0.6.0, and on https://rubygems.org/gems/em-websocket/versions/0.5.2, it refers to the older version.   Thanks.

**Comment by igrigorik** [comment]
Resolved via #159.
