### ISSUE TITLE
Best way to integrate with Rails 3?

### ISSUE THREAD

**Issue by anand-zz** [igrigorik/em-websocket#21]
When I run the code within examples/echo.rb in a Rails 3 initializer, it errors out on the first message with a process_data error. The same code runs fine outside Rails in a standalone program. What could be the issue here ?

```
em-websocket/framing76.rb:67:in `process_data': 134217727: /\A\x00([^\xff]*)\xff/ (SyntaxError)
```

(The above is a simple test case. It actually needs to be done within a thread so that the rest of the rails 3 initialization proceeds. This was just a test case which was on jRuby; client was chrome running examples/test).

On a related note, what is the best practice to integrate em-websocket within Rails 3 for just sending notification messages via a web service?

**Comment by SergeiStruk** [comment]
You can put your em script into initializer. Example: https://gist.github.com/SergeiStruk/084fa44482c0a2f27727.
