### ISSUE TITLE
How to host on Heroku?

### ISSUE THREAD

**Issue by andrewhavens** [igrigorik/em-websocket#68]
I've been trying to find some example somewhere of how to host an em-websocket app on Heroku and can't seem to find anything anywhere. I'm also new to EventMachine, so that doesn't help.

Can you please add some documentation to the wiki, or Readme that explains how you would go about hosting this on Heroku?

Thanks!

**Comment by ErikAGriffin** [comment]
I would also like an example of a Heroku server running an em-websocket server, if they do indeed support such architectures now.  I will continue investigating on my own and post my results here if successful.
